language: php

php: ["5.3", "5.4", "5.5"]

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "UKSpkbbxP62R8wUFrkWM6u8fmkzS85OugzaMWrx1qZTCEQ3AqdxtfLUg6SmE7ALjRQZS/CUPUZmTM05b1CsozLtk/Ehq86fNz12lWzVadfOq4J1ot9YsR5pFHb3PMusQdYZwEOppb/CAa4/FTR/K8mels4/cLclkem+kCogFTTQ="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
